---
- name: install fluetnd and cloud_sql_proxy
  hosts: gcp_environment_dev
  become_user: root
  become_method: sudo
  roles:
    - role: bookshelf
  vars:
    backend: "'cloudsql'"
    project_id: "'arcane-bit-349310'"
    user: "'root'"
    password: "'1234'"
    database: "'dey'"
    connection_name: "'arcane-bit-349310:us-central1:sd35'"
    bucket: "'tf-static-bucket-1s'"
    port: "8080"