---
- name: install fluetnd and cloud_sql_proxy
  hosts: localhost
  become_user: root
  become_method: sudo
  roles:
    - bookshelf
  vars:
    backend: "'cloudsql'"
    project_id: "'arcane-bit-349310'"
    user: "'root'"
    password: "'1234'"
    database: "'dey'"
    connection_name: "'arcane-bit-349310:us-central1:ansible-dey'"
    bucket: "'my_bucket_new1'"
    port: "8080"